export enum ActionTypes {
  LOAD_CURRENT_USER_INFO = 'LOAD_CURRENT_USER_INFO [Auth Component]',
  LOAD_CURRENT_USER_INFO_SUCCESS = 'LOAD_CURRENT_USER_INFO_SUCCESS [Auth Component]',
  LOAD_CURRENT_USER_INFO_FAIL = 'LOAD_CURRENT_USER_INFO_FAIL [Auth Component]',

  REGISTRATION_OF_USER = 'REGISTRATION_OF_USER [Auth Component]',
  REGISTRATION_OF_USER_SUCCESS = 'REGISTRATION_OF_USER_SUCCESS [Auth Component]',
  REGISTRATION_OF_USER_FAIL = 'REGISTRATION_OF_USER_FAIL [Auth Component]',

  AUTHENTICATION_OF_USER = 'AUTHENTICATION_OF_USER [Auth Component]',
  AUTHENTICATION_OF_USER_SUCCESS = 'AUTHENTICATION_OF_USER_SUCCESS [Auth Component]',
  AUTHENTICATION_OF_USER_FAIL = 'AUTHENTICATION_OF_USER_FAIL [Auth Component]',

  LOAD_ALL_USERS = 'LOAD_ALL_USERS [Auth Component]',
  LOAD_ALL_USERS_SUCCESS = 'LOAD_ALL_USERS_SUCCESS [Auth Component]',
  LOAD_ALL_USERS_FAIL = 'LOAD_ALL_USERS_FAIL [Auth Component]'
}
