export enum ActionTypes {
  LOAD_CURRENT_USER_INFO = 'LOAD_CURRENT_USER_INFO [Auth Component]',
  LOAD_CURRENT_USER_INFO_SUCCESS = 'LOAD_CURRENT_USER_INFO_SUCCESS [Auth Component]',
  LOAD_CURRENT_USER_INFO_FAIL = 'LOAD_CURRENT_USER_INFO_FAIL [Auth Component]',

  REGISTRATION_OF_USER = 'REGISTRATION_OF_USER [Auth Component]',
  REGISTRATION_OF_USER_SUCCESS = 'REGISTRATION_OF_USER_SUCCESS [Auth Component]',
  REGISTRATION_OF_USER_FAIL = 'REGISTRATION_OF_USER_FAIL [Auth Component]',
}
